In [2]:
import pandas as pd
from pathlib import Path

In [5]:
interim_df = pd.read_parquet("../data/interim/lastfm/lastfm_scrobbles_merged.parquet")

In [6]:
interim_df

                artist                     track   timestamp  year_file
0                Oasis  Don't Look Back in Anger  1199052426       2007
1                Oasis                Wonderwall  1199052167       2007
2                Oasis  Don't Look Back in Anger  1199051867       2007
3                Oasis                Wonderwall  1199051609       2007
4              Incubus      Aqueous Transmission  1199051161       2007
...                ...                       ...         ...        ...
559444  Perfume Genius            No Front Teeth         NaN       2026
559445  Perfume Genius            No Front Teeth         NaN       2026
559446  Perfume Genius            No Front Teeth         NaN       2026
559447  Perfume Genius            No Front Teeth         NaN       2026
559448  Perfume Genius            No Front Teeth         NaN       2026

[559449 rows x 4 columns]

In [10]:
# 1. Drop rows with missing timestamps
df = interim_df.dropna(subset=["timestamp"])
df

,artist,track,timestamp,year_file
0,Oasis,Don't Look Back in Anger,1199052426,2007
1,Oasis,Wonderwall,1199052167,2007
2,Oasis,Don't Look Back in Anger,1199051867,2007
3,Oasis,Wonderwall,1199051609,2007
4,Incubus,Aqueous Transmission,1199051161,2007
...,...,...,...,...
558996,Alaskan Tapes,Wait,1767473119,2026
558997,Brian Eno,An Ending (Ascent) - Remastered 2005,1767472882,2026
558998,Michael Andrews,Boy Moves The Sun,1767472698,2026
558999,Stellardrone,Tranquility,1767472374,2026
559000,The Horrors,Weighed Down,1767472349,2026

In [9]:
# 2. Convert timestamps to datetime and extract year and month
df["timestamp"] = pd.to_numeric(df["timestamp"], errors="coerce")
df["timestamp"] = df["timestamp"].astype(int)
df["played_at"] = pd.to_datetime(df["timestamp"], unit="s")
df["year"] = df["played_at"].dt.year
df["month"] = df["played_at"].dt.to_period("M")
df

,artist,track,timestamp,year_file,played_at,year,month
0,Oasis,Don't Look Back in Anger,1199052426,2007,2007-12-30 22:07:06,2007,2007-12
1,Oasis,Wonderwall,1199052167,2007,2007-12-30 22:02:47,2007,2007-12
2,Oasis,Don't Look Back in Anger,1199051867,2007,2007-12-30 21:57:47,2007,2007-12
3,Oasis,Wonderwall,1199051609,2007,2007-12-30 21:53:29,2007,2007-12
4,Incubus,Aqueous Transmission,1199051161,2007,2007-12-30 21:46:01,2007,2007-12
...,...,...,...,...,...,...,...
558996,Alaskan Tapes,Wait,1767473119,2026,2026-01-03 20:45:19,2026,2026-01
558997,Brian Eno,An Ending (Ascent) - Remastered 2005,1767472882,2026,2026-01-03 20:41:22,2026,2026-01
558998,Michael Andrews,Boy Moves The Sun,1767472698,2026,2026-01-03 20:38:18,2026,2026-01
558999,Stellardrone,Tranquility,1767472374,2026,2026-01-03 20:32:54,2026,2026-01
559000,The Horrors,Weighed Down,1767472349,2026,2026-01-03 20:32:29,2026,2026-01

In [15]:
# 4. Sanity check
print(f"{df.shape} records after processing.")
print(f"Number of empty rows {df.isna().sum()}")
print(f"Number of unique artists in the df {df.artist.nunique()}")
print(f"Number of unique tracks in the df {df.track.nunique()}")
print(f"Top rows {df.head()}")

(550151, 4) records after processing.
Number of empty rows artist       0
track        0
timestamp    0
year_file    0
dtype: int64
Number of unique artists in the df 13837
Number of unique tracks in the df 69106
Top rows     artist                     track   timestamp  year_file
0    Oasis  Don't Look Back in Anger  1199052426       2007
1    Oasis                Wonderwall  1199052167       2007
2    Oasis  Don't Look Back in Anger  1199051867       2007
3    Oasis                Wonderwall  1199051609       2007
4  Incubus      Aqueous Transmission  1199051161       2007

In [18]:
# 5. Deduplication
df.duplicated(subset=["artist", "track", "timestamp"]).sum()
df = df.drop_duplicates(subset=["artist", "track", "timestamp"])
df

,artist,track,timestamp,year_file
0,Oasis,Don't Look Back in Anger,1199052426,2007
1,Oasis,Wonderwall,1199052167,2007
2,Oasis,Don't Look Back in Anger,1199051867,2007
3,Oasis,Wonderwall,1199051609,2007
4,Incubus,Aqueous Transmission,1199051161,2007
...,...,...,...,...
558996,Alaskan Tapes,Wait,1767473119,2026
558997,Brian Eno,An Ending (Ascent) - Remastered 2005,1767472882,2026
558998,Michael Andrews,Boy Moves The Sun,1767472698,2026
558999,Stellardrone,Tranquility,1767472374,2026
559000,The Horrors,Weighed Down,1767472349,2026

In [62]:
# 6. Cleaning artist names
import re

def clean_text_artist(text):
    if text is None:
        return None
    
    text = text.lower()
    
    # remove brackets (artist rarely has any important info in brackets)
    text = re.sub(r"\(.*?\)", "", text)
    
    # remove strange suffixes
    text = re.sub(r"\d{2,}[a-z]{3,}\d*$", "", text)
    
    # remove " - something"
    text = re.sub(r"\s-\s.*", "", text)

    # remove special characters
    text = re.sub(r"[^a-z0-9\s]", "", text)

    # normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text if text else None

In [63]:
# 7. Cleaning track names

def clean_text_track(text):
    if text is None:
        return None
    
    text = text.lower()
    
    # Remove content in parentheses that is not part of the title
    text = re.sub(
        r"\((?:"
        r"feat\.?.*?|ft\.?.*?|"
        r"remaster(?:ed)?(?: \d{4})?|"
        r"live(?: at .*?)?|"
        r"radio edit|edit|"
        r"(?:acoustic|alternative|instrumental)(?: version)?|"
        r"mix|version|"
        r"deluxe|bonus track|"
        r"single version"
        r")\)",
        "",
        text,
    )
    
    # remove feat/ft also if outside brackets
    text = re.sub(r"\b(feat|ft)\.?\b.*", "", text)
    
    # 🔥 remove remix/rework/edit/version also if outside brackets
    text = re.sub(r"\b(remix|rework|edit|version)\b.*", "", text)
    
    # remove strange suffixes
    text = re.sub(r"\d{2,}[a-z]{3,}\d*$", "", text)
    
    # remove " - something"
    text = re.sub(r"\s-\s.*", "", text)

    # remove special characters
    text = re.sub(r"[^a-z0-9\s]", "", text)

    # normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text if text else None

In [64]:
df["artist_clean"] = df["artist"].apply(clean_text_artist)
df["track_clean"] = df["track"].apply(clean_text_track)

In [68]:
df = df.dropna(subset=["track_clean"])

In [71]:
print("Before:", df["track"].nunique())
print("After:", df["track_clean"].nunique())

print("Before:", df["artist"].nunique())
print("After:", df["artist_clean"].nunique())

Before: 68803
After: 58535
Before: 13773
After: 13701

In [73]:
df[["track", "track_clean"]].sample(50)

,track,track_clean
424822,Brother the Cloud,brother the cloud
462697,Only A Moment,only a moment
296629,To Be Loved,to be loved
165569,Diamonds,diamonds
281307,Wake Up Call,wake up call
327671,Anywhere,anywhere
321428,Planet Caravan,planet caravan
368662,Wild Horses - Live / Remastered 2009,wild horses
41116,Timshel,timshel
139781,Pet,pet
465044,Extraordinary Machine,extraordinary machine
91020,Dance With Me,dance with me
269055,10 Mile Stereo - Cough Syrup Remix,10 mile stereo
336472,Macro,macro
381060,What's a Girl to Do?,whats a girl to do
163862,God Save the Queen,god save the queen
544936,The Politics of Orgasm,the politics of orgasm
82339,Asleep,asleep
257810,Moonshine Freeze,moonshine freeze
474241,Words In My Head,words in my head
125675,Bubbles,bubbles
500951,4141,4141
503491,Sugar for the Pill,sugar for the pill
260200,Bricks and Mortar,bricks and mortar
160600,The Night,the night
420922,To Hell & Back Again,to hell back again
233349,Father's Child,fathers child
493577,Bliss,bliss
163749,Indian Summer,indian summer
409000,Cosmic Dancer,cosmic dancer
263228,Sunrise (Pillows),sunrise pillows
334083,Soul Love - 2012 Remaster,soul love
95019,Move in the Right Direction,move in the right direction
430958,Shadow Moses,shadow moses
535080,Glare,glare
8216,I Know You Are But What Am I,i know you are but what am i
433434,"Say, Can You Hear",say can you hear
311129,Another one goes by,another one goes by
435523,Comin' Back to Me,comin back to me
100793,B.B. Chevelle,bb chevelle
328296,About Today,about today
557442,Where's My Phone?,wheres my phone
479766,New Love Cassette (Mark Ronson Remix),new love cassette mark ronson
76228,The Devil's Daughter,the devils daughter
22334,What Else is There (Jacques Lu Cont Radio Mix),what else is there jacques lu cont radio mix
245855,Every Breaking Wave,every breaking wave
540857,Funny Time Of Year,funny time of year
372723,Espionage,espionage
335676,I Don't Belong,i dont belong
146059,Unfold,unfold

In [61]:
df[["artist", "artist_clean"]].sample(50)

,artist,artist_clean
459776,Japanese Breakfast,japanese breakfast
348134,Minor Victories,minor victories
491370,Japanese Breakfast,japanese breakfast
540285,Oberhofer,oberhofer
538874,Autechre,autechre
489649,Japanese Breakfast,japanese breakfast
246659,The Smiths,the smiths
485718,Deftones,deftones
183780,BANKS,banks
54756,Joy Division,joy division
504645,Voo Voo,voo voo
265966,Sadness,sadness
91473,Red Hot Chili Peppers,red hot chili peppers
265473,Portishead,portishead
346720,Hope Sandoval and The Warm Inventions,hope sandoval and the warm inventions
217445,Carbon Based Lifeforms,carbon based lifeforms
263898,Fisz Emade Tworzywo,fisz emade tworzywo
98715,Arms and Sleepers,arms and sleepers
293481,Twin Peaks,twin peaks
437382,Dusty Springfield,dusty springfield
58648,Kings of Leon,kings of leon
167346,Kortez,kortez
359157,Tori Amos,tori amos
161351,Depeche Mode,depeche mode
79196,Danny Elfman,danny elfman
504404,Atmos Bloom,atmos bloom
367613,The Libertines,the libertines
222156,Deftones,deftones
129587,Thirty Seconds to Mars,thirty seconds to mars
508071,Rob Lane,rob lane
149179,The Neighbourhood,the neighbourhood
487751,Orchestral Manoeuvres in the Dark,orchestral manoeuvres in the dark
156472,Jack Johnson,jack johnson
96755,T.Love,tlove
76654,Cat Power,cat power
342523,Fleetwood Mac,fleetwood mac
109989,The Smiths,the smiths
27096,The Walkmen,the walkmen
171558,Julia Marcell,julia marcell
173844,Al Green,al green
418583,The Afghan Whigs,the afghan whigs
271035,PJ Harvey,pj harvey
557915,Orbital,orbital
306486,Kings of Leon,kings of leon
88854,Jude,jude
213670,Amber Run,amber run
322936,Grouper,grouper
215993,Tame Impala,tame impala
450553,Portico Quartet,portico quartet
416533,TV on the Radio,tv on the radio

In [49]:
df["parentheses"] = df["track"].apply(lambda x: re.findall(r"\(.*?\)", x.lower()))

In [52]:
df["parentheses"].explode().value_counts().head(30)

parentheses
(live)                                     648
(remastered)                               618
(acoustic)                                 551
(bonus track)                              400
(a deal with god)                          261
(don't fear)                               233
(feat. jack liebeck)                       216
(demo)                                     208
(cosi fan tutte)                           190
(album version)                            177
(instrumental)                             163
(in the house of flies)                    157
(omnimotion feat. krister linder remix)    151
(far away)                                 144
(intro)                                    142
(single version)                           130
(feat. bruce springsteen)                  130
(feat. alison mosshart)                    110
(ascent)                                   109
(reprise)                                  106
(radio edit)                                95
(xo)                                        94
(this kind of love)                         88
(in c for two virgins)                      87
(naive melody)                              86
(feat. ian astbury)                         84
(night talking)                             83
(i'll put a spell on you)                   81
(night)                                     81
(act i and ii)                              80
Name: count, dtype: int64

In [74]:
df.to_parquet(
    "../data/processed/lastfm_scrobbles_clean.parquet",
    index=False
)