In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
analysis_df = pd.read_csv(
    "../data/processed/final/music_taste_analysis_ready.csv"
)

In [4]:
# Top artist by Era

def assign_era(year):
    if year <= 2011:
        return "2008-2011"
    elif year <= 2016:
        return "2012-2016"
    elif year <= 2021:
        return "2017-2021"
    else:
        return "2022-2025"

analysis_df["era"] = analysis_df["year_file"].apply(assign_era)

In [5]:
# Distribution of the analytical dataset across macro-clusters and eras

macro_era_counts = (
    analysis_df
    .groupby(["macro_cluster", "era"])
    .size()
    .unstack(fill_value=0)
)

macro_era_counts

era                   2008-2011  2012-2016  2017-2021  2022-2025
macro_cluster
Alternative Core           3413       7147      14750      11986
Electronic & Ambient        974       3092       6530       5671
Rock & Britrock            2405       3384       6144       3351
Singer-Songwriter           574       1039       1156       1207

In [7]:
# Percentage distribution of the analytical dataset across macro-clusters and eras

macro_era_pct = (
    macro_era_counts
    .div(macro_era_counts.sum().sum())
    * 100
)

macro_era_pct.round(1)

era                   2008-2011  2012-2016  2017-2021  2022-2025
macro_cluster
Alternative Core            4.7        9.8       20.3       16.5
Electronic & Ambient        1.3        4.2        9.0        7.8
Rock & Britrock             3.3        4.6        8.4        4.6
Singer-Songwriter           0.8        1.4        1.6        1.7

In [8]:
macro_era_counts.sum().sum(), len(analysis_df)

(72823, 72823)

In [9]:
analysis_df.shape

(72823, 16)

In [10]:
analysis_df[["artist", "track"]].drop_duplicates().shape

(72823, 2)

In [11]:
analysis_df.duplicated(["artist", "track"]).sum()

0

In [12]:
analysis_df[["artist_clean", "track_clean"]].drop_duplicates().shape

(72823, 2)

In [13]:
analysis_df.duplicated(["artist_clean", "track_clean"]).sum()

0

In [14]:
analysis_df[
    (analysis_df["artist_clean"] == "incubus") &
    (analysis_df["track_clean"] == "under my umbrella")
][
    ["artist", "track", "artist_clean", "track_clean", "year_file"]
].head(20)

,artist,track,artist_clean,track_clean,year_file
3,Incubus,Under My Umbrella12DSGMS192,incubus,under my umbrella,2007